### ISSUE TITLE
Config - Partage FB (URL app's domain)  - Version EN.

### ISSUE THREAD

**Issue by Lu7sodaa** [Skoli-Code/IDLM-static#36]
<img width="559" alt="capture d ecran 2017-01-05 a 15 32 28" src="https://cloud.githubusercontent.com/assets/8087504/21684026/3f26391c-d35c-11e6-81d2-01d2171bc123.png">

**Comment by pbellon** [comment]
J'ai mis à jour les paramètres de l'application Facebook et ça devrait être bon maintenant.
